version: "3.1"
services:
  database:
    image: mysql:5.7
    volumes:
      - ./mysql/db/entrypoint:/docker-entrypoint-initdb.d/
      - ./mysql/db/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./data_for_import:/var/lib/mysql-files
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=geheim"
      - "MYSQL_DATABASE=foren"